name: Deploy

concurrency: production

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: Deploy
    
    runs-on: ubuntu-latest
    
    environment: production
    
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "toml-file-editor"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
